# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a535e60b57549916d60d81844f08bed95c401aecf4e80f7677e62696ea812fa9a6e40c838b6c4707d3e00a0d9a4b9be1fa72b97384eefe57e6a6a6d2f3873ebe

test:
  secret_key_base: 9532be1659c6b3b021651681e8ff74c6d09bcf4bb41d7f2455f975da5e22065c62a213411bd0a520e016ef76e921d57272f6cb621af130bbc3f57c17b5a84e58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
